@echo off
echo Building Tasky for Windows...

echo Installing dependencies...
call npm install

echo Building renderer...
call npm run build-renderer

echo Building electron modules...
call npm run build-electron

echo Starting application...
call npm run start

pause